### ISSUE TITLE
sync a special directory inside of webserver container

### ISSUE THREAD

**Issue by Jehu** [leighmcculloch/docker-unison#12]
i try to figure out how to sync /var/www/html from [this image](https://github.com/drupal-docker/php/blob/master/7.0/apache/Dockerfile).

I use docker-compose with a docker-compose.yml like this:

```
version: '2'
services:
  web:
    image: drupaldocker/php:apache
    volumes_from:
        - unison
    ports:
      - "8080:80"
    links:
      - db
    depends_on:
      - unison
      - db
      - solr
  db:
    image: bitnami/mariadb
    environment:
      MARIADB_DATABASE: drupal
      MARIADB_PASSWORD: rootroot
    ports:
      - "3306:3306"
  unison:
    image: leighmcculloch/unison
    environment:
      - UNISON_VERSION=2.48.3
      - UNISON_WORKING_DIR=/var/www/html
      - WORKDIR=/var/www/html
    ports:
      - "5000:5000"
  solr:
      image: mxr576/apachesolr-5.x-drupal-docker
      ports:
        - 8983:8983
      environment:
        PARTIAL_SEARCH_ENABLED: 'true'
```

But after the command
`unison /Users/marco/path/to/my/project/www/ socket://localhost:5000/ -ignore 'Path .git' -auto -batch` the /var/www/html inside the web container is empty

**Comment by leighmcculloch** [comment]
@Jehu Is unison on your host machine outputting an error? Can you tail the docker logs and share what the image is showing?

**Comment by jujes** [comment]
Hi, I have the same issue, my special directory is: **/var/www/htdocs**

**logs**

```
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 8
./run: 3: cd: can't cd to /var/www/htdocs
Jul 30 17:21:33 55cb620b097c syslog-ng[15]: syslog-ng starting up; version='3.5.3'
```

**docker-compose.yml**

```
web:
  build: .
  ports:
    - "80:80"
  links:
    - mysql
  env_file:
    - env
  volumes_from:
    - unison
mysql:
  image: mysql:5.6.23
  env_file:
    - env
unison:
  image: leighmcculloch/unison:latest
  environment:
    - UNISON_WORKING_DIR=/var/www/htdocs
    - WORKDIR=/var/www/htdocs
  ports:
    - "5000:5000"
```

Someone know how keep sync my Magento folder whit Unison?

thanks in advance,
