### ISSUE TITLE
Doesn't seems to improve speed

### ISSUE THREAD

**Issue by Briones** [leighmcculloch/docker-unison#20]
Maybe I'm doing all wrong, I don't know, I'm trying to use this project with Dinghy in Mac, with the following docker-compose.yml

```
project:
  build: .
  dockerfile: ./Dockerfile.app
  expose:
    - "9000"
    - "9001"
  links:
    - redis
  container_name: app
  volumes:
    - /Users/roberto.briones/Documents/project:/var/www/project
  volumes_from:
    - unison

redis:
  image: redis:3.0.6
  container_name: cache
  ports:
    - "6379:6379"

webserver:
  build: .
  dockerfile: ./Dockerfile.nginx
  ports:
    - "80:80"
    - "443:443"
  container_name: nginx
  links:
    - project
  volumes:
    - ./logs/nginx:/var/log/nginx
  volumes_from:
    - project:ro

unison:
  image: leighmcculloch/unison:latest
  environment:
    - UNISON_WORKING_DIR=/unison
  volumes:
    - /unison
  ports:
    - "5000:5000"
```

My symfony project is in `/Users/roberto.briones/Documents/project` and that's the folder that I want to speed up, I follow the steps in the README but I don't know if my configuration is correct, also maybe this project is instead of using Dinghy, can anyone give me a hand with this?
